// Own header.
#include "FS_STM32F4xxPinMux.h"

#include "stm32f4xx_conf.h"


static void * afMap[139][15] = {
{ NULL, TIM2, TIM5, TIM8, NULL, NULL, NULL, USART2, UART4, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM2, TIM5, NULL, NULL, NULL, NULL, USART2, UART4, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM2, TIM5, TIM9, NULL, NULL, NULL, USART2, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM2, TIM5, TIM9, NULL, NULL, NULL, USART2, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, SPI1, I2S3, USART2, NULL, NULL, OTG_HS, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, TIM2, NULL, TIM8, NULL, SPI1, NULL, NULL, NULL, NULL, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, TIM3, TIM8, NULL, SPI1, NULL, NULL, NULL, TIM13, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, TIM3, TIM8, NULL, SPI1, NULL, NULL, NULL, TIM14, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, I2C3, NULL, NULL, USART1, NULL, NULL, OTG_FS, NULL, OTG_FS, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, I2C3, NULL, NULL, USART1, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, USART1, NULL, NULL, OTG_FS, NULL, OTG_FS, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, USART1, NULL, CAN1, OTG_FS, NULL, OTG_FS, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, USART1, NULL, CAN1, OTG_FS, NULL, OTG_FS, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, SPI1, I2S3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, TIM3, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, TIM3, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM2, NULL, NULL, NULL, SPI1, I2S3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM3, NULL, NULL, SPI1, I2S3, I2S3ext, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM3, NULL, I2C1, SPI1, I2S3, NULL, NULL, CAN2, OTG_HS, ETH, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, I2C1, NULL, NULL, USART1, NULL, CAN2, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, I2C1, NULL, NULL, USART1, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, TIM4, TIM10, I2C1, NULL, NULL, NULL, NULL, CAN1, NULL, ETH, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, TIM4, TIM11, I2C1, I2S2, NULL, NULL, NULL, CAN1, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, TIM2, NULL, NULL, I2C2, I2S2, NULL, USART3, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM2, NULL, NULL, I2C2, NULL, NULL, USART3, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, I2C2, I2S2, NULL, USART3, NULL, CAN2, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, I2S2, NULL, USART3, NULL, CAN2, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, TIM8, NULL, I2S2ext, NULL, USART3, NULL, TIM12, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, TIM8, NULL, I2S2, NULL, NULL, NULL, TIM12, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, I2S2ext, NULL, NULL, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, I2S2, NULL, NULL, NULL, NULL, OTG_HS, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM3, TIM8, NULL, I2S2, NULL, NULL, USART6, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM3, TIM8, NULL, NULL, I2S3, NULL, USART6, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM3, TIM8, NULL, NULL, NULL, NULL, USART6, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM3, TIM8, I2C3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, I2S3, USART3, UART4, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, SPI3, USART3, UART4, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, I2S3, USART3, UART5, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAN1, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAN1, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM3, NULL, NULL, NULL, NULL, NULL, UART5, NULL, NULL, NULL, SDIO, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART2, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART2, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART2, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART2, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART2, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART3, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART3, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART3, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART3, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, NULL, NULL, NULL, USART3, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, TIM4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, TIM10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, TIM11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TIM13, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TIM14, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, NULL, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, ETH, FSMC, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, USART6, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, NULL, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, I2C2, NULL, NULL, NULL, NULL, TIM12, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C3, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, I2C3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, TIM1, NULL, NULL, I2C3, NULL, NULL, NULL, NULL, TIM12, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, CAN1, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, TIM5, NULL, NULL, I2S2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, I2S2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, I2S2ext, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, I2S2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL,void FS_STM32F4xxUSART_InitStructInit(FS_STM32F4xxUSART_InitStruct_t * initStruct) NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, TIM8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DCMI, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, CAN1, NULL, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ETH, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, OTG_HS, NULL, NULL, NULL, NULL, EVENTOUT },
{ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, EVENTOUT }
};

void FS_STM32F4xxPinMux_Init(FS_STM324xxPinMux_t * instance)
{
  // Assign the pointers in the interface struct.
  instance->runPort = runPort;
  instance->setPinFunction = setPinFunction;
}

static void(*runPort)(FS_STM32F4xxMuxablePinPort_e port)
{

}

static _Bool setPinFunction(FS_STM32F4xxMuxablePin_t pin, void * peripheral)
{
  uint8_t tableIndex, i;
  _Bool success;
  uint32_t portBaseAddress;

  tableIndex = (uint8_t)pin.port * 16 + (uint8_t)pin.bit;

  // Locate the AF number of the peripheral.
  for(i = 0; i < 15, i++)
  {
    if(peripheral == afMap[tableIndex][i])
    {
      success = true;
      break;
    }
  }

  // If the requested function is not available on the pin, return an error.
  if(!success)
  {
    return false;
  }

  portBaseAddress = GPIOA_BASE + ( 0x400 * (uint8_t)pin.port );
  GPIO_PinAFConfig( ( GPIO_TypeDef * )portBaseAddress, (uint8_t)pin.bit, i );
  return true;
}
